<a href="https://colab.research.google.com/github/richa1288/Tensorflow/blob/main/Basic_tensor_module1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install tensorflow

     |████████████████████████████████| 462 kB 5.0 MB/s 


In [4]:
%tensorflow_version 2.x 
import tensorflow as tf


In [6]:
# Creating Tensors
string = tf.Variable("This is a string", tf.string)
number= tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

In [16]:
# Degree of tensorsor the number of dimension in the tensor.

rank1_tensor = tf.Variable(["Test"], tf.string) 
rank2_tensor = tf.Variable([["test", "ok", "no"], ["test", "yes", "no"]], tf.string)
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [18]:
# Shapes of tensor  # 2 list and 3 elements in each list
rank2_tensor.shape    

TensorShape([2, 3])

In [19]:
#Changing of shape
tensor1= tf.ones([1,2,3])
print(tensor1)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [21]:
tensor2 = tf.reshape(tensor1, [2,3,1])
print(tensor2)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
